apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: engagement-app-pipeline
description: Delivery pipeline for Engagement App API V4
serialPipeline:
  stages:
  - targetId: testing
    profiles: []
    strategy:
      standard:
        verify: true
  - targetId: staging
    profiles: []
    strategy:
      standard:
        verify: true
  - targetId: production
    profiles: []
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25, 50, 75]
          verifyInterval: 300s
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: testing
description: Testing environment
run:
  location: projects/${PROJECT_ID}/locations/${REGION}
  serviceAccount: ${SERVICE_ACCOUNT}
  executionConfigs:
  - usages: ["RENDER", "DEPLOY"]
    serviceAccount: ${SERVICE_ACCOUNT}
  cloudRun:
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "0.5"
        memory: 256Mi
    containerConcurrency: 80
    timeoutSeconds: 300
    allowUnauthenticated: true
    scaling:
      minInstanceCount: 1
      maxInstanceCount: 3
    healthCheck:
      path: "/status"
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 3
      successThreshold: 1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging environment
run:
  location: projects/${PROJECT_ID}/locations/${REGION}
  serviceAccount: ${SERVICE_ACCOUNT}
  executionConfigs:
  - usages: ["RENDER", "DEPLOY"]
    serviceAccount: ${SERVICE_ACCOUNT}
  cloudRun:
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 512Mi
    containerConcurrency: 80
    timeoutSeconds: 300
    allowUnauthenticated: true
    scaling:
      minInstanceCount: 1
      maxInstanceCount: 5
    healthCheck:
      path: "/status"
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 3
      successThreshold: 1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production environment
run:
  location: projects/${PROJECT_ID}/locations/${REGION}
  serviceAccount: ${SERVICE_ACCOUNT}
  executionConfigs:
  - usages: ["RENDER", "DEPLOY"]
    serviceAccount: ${SERVICE_ACCOUNT}
  cloudRun:
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
    containerConcurrency: 100
    timeoutSeconds: 300
    allowUnauthenticated: true
    scaling:
      minInstanceCount: 2
      maxInstanceCount: 10
      cpuUtilization:
        targetUtilizationPercent: 70
    healthCheck:
      path: "/status"
      initialDelaySeconds: 15
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 3
      successThreshold: 1
    traffic:
      - percent: 100
        type: TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST
    rollbackPolicy:
      onFailure: true
      onHealthCheckFailed: true
      timeoutSeconds: 600
